table 'Table 1 (Food_Details)'
	lineageTag: d140c3a7-4eea-4025-b898-e3252d6a1337

	column ItemCode
		dataType: int64
		formatString: 0
		lineageTag: c3dde4f7-fd29-4c73-bcee-4238ec638317
		summarizeBy: none
		sourceColumn: ItemCode

		annotation SummarizationSetBy = Automatic

	column 'Food Name'
		dataType: string
		lineageTag: bf5757cb-5bdf-4b61-8eb8-10ae344884be
		summarizeBy: none
		sourceColumn: Food Name

		annotation SummarizationSetBy = Automatic

	column Food_Type
		dataType: string
		lineageTag: 84ab5f8a-abeb-45f4-b8ab-fb4b379d74c5
		summarizeBy: none
		sourceColumn: Food_Type

		annotation SummarizationSetBy = Automatic

	column Column4
		dataType: string
		lineageTag: 1a6b57db-20e8-42f5-ae59-d3e8ab4b7771
		summarizeBy: none
		sourceColumn: Column4

		annotation SummarizationSetBy = Automatic

	partition 'Table 1 (Food_Details)' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\jinka\OneDrive\Desktop\pow_bi\Learn Power BI in 7 Hours  Full Beginner to Advanced Course with Dashboard Project_2025\Day - 1 to Day - 10 - Other_Data PBI Pract Satish.xlsx"), null, false),
				    Food_Details_sheet = Source{[Item="Food_Details",Kind="Sheet"]}[Data],
				    FilterNullAndWhitespace = each List.Select(_, each _ <> null and (not (_ is text) or Text.Trim(_) <> "")),
				    #"Transposed Table" = Table.Transpose(Food_Details_sheet),
				    #"Added Custom" = Table.AddColumn(#"Transposed Table", "IsEmptyRow", each try List.IsEmpty(FilterNullAndWhitespace(Record.FieldValues(_))) otherwise false),
				    #"Added Index" = Table.AddIndexColumn(#"Added Custom", "Index", -1),
				    #"Added Custom1" = Table.AddColumn(#"Added Index", "Section", each if [IsEmptyRow] then -1 else if try #"Added Index"[IsEmptyRow]{[Index]} otherwise true then [Index] else null),
				    #"Removed Blank Rows" = Table.SelectRows(#"Added Custom1", each not [IsEmptyRow]),
				    #"Filled Down" = Table.FillDown(#"Removed Blank Rows", {"Section"}),
				    #"Grouped Rows" = Table.Group(#"Filled Down", {"Section"}, {{"Rows", each _}}, GroupKind.Local),
				    #"Selected Group" = #"Grouped Rows"[Rows]{0},
				    #"Removed Columns" = Table.RemoveColumns(#"Selected Group", {"IsEmptyRow", "Index", "Section"}),
				    #"Transposed Table1" = Table.Transpose(#"Removed Columns"),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Transposed Table1", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ItemCode", Int64.Type}, {"Food Name", type text}, {"Food_Type", type text}, {"Column4", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

